export const CREATE_COURSE = 'COURSE/CREATE_COURSE';

export const FETCH_POSTS = 'POSTS/FETCH_POSTS';
export const SUCCESS_POSTS = 'POSTS/SUCCESS_POSTS';
export const FAILED_POSTS = 'POSTS/FAILED_POSTS';
